In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
dep_csv = pd.read_csv('submit.csv')

In [61]:
indep_csv = pd.read_csv('test.csv')
indep_csv.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [62]:
df= pd.concat([indep_csv,dep_csv], axis = 1)

In [63]:
df = df.dropna()

In [64]:
df.isnull().sum()

id        0
title     0
author    0
text      0
id        0
label     0
dtype: int64

In [65]:
df.reset_index(inplace=True)

In [66]:
indep_var = df.drop(['id','label'], axis =1)

In [67]:
indep_var.head()

index                                              title  \
0      0  Specter of Trump Loosens Tongues, if Not Purse...   
1      2  #NoDAPL: Native American Leaders Vow to Stay A...   
2      3  Tim Tebow Will Attempt Another Comeback, This ...   
3      4                    Keiser Report: Meme Wars (E995)   
4      6  Pelosi Calls for FBI Investigation to Find Out...   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
2            Daniel Victor  If at first you don’t succeed, try a different...  
3  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...  
4                  Pam Key  Sunday on NBC’s “Meet the Press,” House Minori...

In [68]:
y = df['label']

In [69]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer

In [70]:
X = indep_var.copy()

In [73]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

In [75]:
ps = PorterStemmer()
corpus = []

for i in range(0,len(X)):
    review = re.sub('[^a-zA-Z]', ' ', X['text'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [78]:
tfidf = TfidfVectorizer(max_features = 5000, ngram_range = (1,3))
X = tfidf.fit_transform(corpus).toarray()

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)

In [82]:
df = pd.DataFrame(X_train, columns = tfidf.get_feature_names())

In [83]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [84]:
from sklearn import metrics
import numpy as np
import itertools

In [88]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
score

0.7574654042243263

In [87]:
cm = metrics.confusion_matrix(y_test, pred)
cm

array([[541, 116],
       [217, 499]], dtype=int64)

#### Passive Aggressive Classifier Algorithm

In [90]:
from sklearn.linear_model import PassiveAggressiveClassifier
pass_agg_class = PassiveAggressiveClassifier()

In [91]:
pass_agg_class.fit(X_train,y_train)

PassiveAggressiveClassifier()

In [92]:
pass_pred = pass_agg_class.predict(X_test)

In [93]:
pass_pred

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [98]:
pass_as = metrics.accuracy_score(y_test,pass_pred)

In [99]:
pass_as

0.8434085943190095

In [100]:
pass_cm = metrics.confusion_matrix(y_test,pass_pred)

In [101]:
pass_cm

array([[551, 106],
       [109, 607]], dtype=int64)

#### Multinomial Classifier

In [102]:
multi_class = MultinomialNB()

In [107]:
for i in np.arange(0,1,0.1):
    mul_class = MultinomialNB(alpha = i)
    mul_class.fit(X_train,y_train)
    mul_pred = mul_class.predict(X_test)
    score = metrics.accuracy_score(y_test,mul_pred)
    print('Alpha {} has Score of {}'.format(i,score))

C:\Users\USER\.conda\envs\virtualenv\lib\site-packages\sklearn\naive_bayes.py:511: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  warnings.warn('alpha too small will result in numeric errors, '


Alpha 0.0 has Score of 0.7545520757465404
Alpha 0.1 has Score of 0.7552804078659869
Alpha 0.2 has Score of 0.752367079388201
Alpha 0.30000000000000004 has Score of 0.7538237436270939
Alpha 0.4 has Score of 0.7560087399854334
Alpha 0.5 has Score of 0.7574654042243263
Alpha 0.6000000000000001 has Score of 0.7596504005826656
Alpha 0.7000000000000001 has Score of 0.7596504005826656
Alpha 0.8 has Score of 0.7567370721048798
Alpha 0.9 has Score of 0.7552804078659869
